apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: otel-collector
  namespace: observability
spec:
  interval: 1h
  url: https://signalfx.github.io/splunk-otel-collector-chart