apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./infrastructure/secrets
  dependsOn:
    - name: namespaces
    - name: sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true