apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stranded-routes
spec:
  parentRefs:
    - name: envoy-gateway
      sectionName: https
      kind: Gateway
      namespace: infra

  hostnames:
    - stranded.blamedevs.com

  rules:
    - backendRefs:
        - name: wilson
          port: 8787
      matches:
        - path:
            type: PathPrefix
            value: /api
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              replacePrefixMatch: /
              type: ReplacePrefixMatch

    - backendRefs:
        - name: stranded-ui
          port: 80