apiVersion: apps/v1
kind: Deployment
metadata:
  name: wilson
  namespace: stranded
  labels:
    app: wilson
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wilson
  template:
    metadata:
      name: wilson
      labels:
        app: wilson
    spec:
      containers:
        - name: wilson
          image: ghcr.io/vaynerakawalo/wilson:cd-202510142209-1fef67e # {"$imagepolicy": "flux-system:wilson-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 8787
              protocol: TCP
          env:
            - name: BARRICADE_PATH
              value: http://barricade.auth.svc.cluster.local:8080
      restartPolicy: Always