{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "elastic-search-es-elastic-user",
    "namespace": "observability"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "elastic-search-es-elastic-user",
        "namespace": "observability"
      }
    },
    "encryptedData": {
      "elastic": "AgBasrss5rrh7Y0X62KNWJlwyIFa1hl/GhjZn52f/+B+wjW7fcLYs6CY6NqukNfB0lod3CNWDrI9zrlqx1XIIkz2amaVUY15cP33J8FGFU+AKnOpMyVgzb8f1GhnTXduGyHTE9tf6sspaD1z8nHLurCxRkM7u6BbrqZ8uUNieHT0/feEGBJZy8slVolAhPhVXP3bajW8hUWym5IvHH5PCP2MA4V9VmVO8Zn4rM+H/AinRN3ERF51aYb+PhcBTvJA50d/GPiulpuQW8NgQEGqyOlPQGqqm62AwTP2wkYwcEh1s7549ECNUQ4Sm3681UdzusQL9Dum1gw7DaRLSe0WGakmoqSM0AsC5NL+wniy5FBJLLeJEpNv4ApsDkCLBNp9nb7tpyqkjmfWBDfe5wl3TpKxJG9i9vxe66Kz333Gq5E8FdppyqJwvKpQz8Z97HuuYPk4sMbb0Zc76en/ic5rF0WpUVs7dKgDOFzTb2c5AovPL9YLvDcdxmaIeOimGNls4RX13DVOzd+jyQGJCJPUd6rRizkUsh00BADuKHhvbwU8FwDgpdf/KsCcybJTVlkH6x8uS22xUilsFhnjt2a5OZobNwr/dIgH8C82DSG4gUKMISfo7w7jxMCgsTkMRxGZFwFsuiDOwm4t2nN0pSR8Bt+QMI/tH64v3uAZCOxhH7MCsGrhco29vq/FsGYFnuRPuH6rUjq2mShA04J+18aVJQ=="
    }
  }
}
