apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: login-ui-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: login-ui-repository
  policy:
    alphabetical:
      order: asc