apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: login-https
  namespace: auth
spec:
  parentRefs:
    - name: envoy-gateway
      sectionName: https
      kind: Gateway
      namespace: infra

  hostnames:
    - auth.blamedevs.com

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /login-ui

        - type: RequestHeaderModifier
          requestHeaderModifier:
            set:
              - name: "Host"
                value: "vaynerakawalo.github.io"

      backendRefs:
        - name: login-ui-external-name
          namespace: auth
          port: 443