apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: auth-route
  namespace: auth
spec:
  parentRefs:
    - name: envoy-gateway
      sectionName: https
      kind: Gateway
      namespace: infra

  hostnames:
    - auth.blamedevs.com

  rules:
    - backendRefs:
        - name: barricade
          port: 8080
      matches:
        - path:
            type: PathPrefix
            value: /api

    - backendRefs:
        - name: login-ui
          port: 80