---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-namespaces
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./infrastructure/namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
