apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-envoy-gateway
  namespace: flux-system
spec:
  interval: 3m0s
  path: ../../infrastructure/envoy-gateway
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true
  dependsOn:
    - name: infrastructure-namespaces
    - name: infrastructure-sealed-secrets
