apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --concurrent=30
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --requeue-dependency=2s
    target:
      kind: Deployment
      name: "(kustomize-controller|helm-controller|source-controller)"