apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-ui
  namespace: auth
  labels:
    app: auth-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-ui
  template:
    metadata:
      name: auth-ui
      labels:
        app: auth-ui
    spec:
      containers:
        - name: auth-ui
          image: ghcr.io/vaynerakawalo/auth-ui:CD-202604092008-3956a32 # {"$imagepolicy": "flux-system:auth-ui-policy"}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
