---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 3m0s
  path: ../../infrastructure/sealed-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 3m0s
  path: ../../infrastructure/namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true