apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gateway
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./deployments/gateway/base
  dependsOn:
    - name: namespaces
    - name: secrets
    - name: envoy-gateway
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true