apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - mc-proxy.yaml
  - mc-server-operator.yaml
  - mc-server-manager.yaml
  - mc-server-cleaner.yaml
  - login-ui.yaml
  - barricade.yaml
  - stranded-ui.yaml