apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mc-server-cleaner
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./deployments/mc-server-cleaner/overlays/prod
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  wait: true