name: IAC cluster changes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "../../provisioning/production/**"
      - ".github/workflows/iac-cluster.yml"

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key Files
        run: |
          mkdir -p ~/.ssh
          
          echo "${{ secrets.SSH_PRV_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519.pub

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup helm
        uses: azure/setup-helm@v4.3.0

      - name: Setup hetzner-kubernetes
        run: |
          wget https://github.com/vitobotta/hetzner-k3s/releases/download/v2.3.9/hetzner-k3s-linux-amd64
          chmod +x hetzner-k3s-linux-amd64
          sudo mv hetzner-k3s-linux-amd64 /usr/local/bin/hetzner-k3s

      - name: Create or update cluster
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_KEY }}
        run: |
          hetzner-k3s create --config provisioning/iac-cluster.yml

      - name: Store kubeconfig as GitHub Secret
        run: |
          echo "${{ secrets.PA_SECRET_TOKEN }}" | gh auth login --with-token

          gh secret set KUBECONFIG_SECRET --body "$(cat kubeconfig)"

      - name: Set kubeconfig from Secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Bootstrap Flux CD
        env:
          GITHUB_TOKEN: ${{ secrets.FLUX_CD_ADMIN_TOKEN }}
        run: |
          flux bootstrap github \
            --owner=${{ github.repository_owner }} \
            --repository=${{ github.event.repository.name }} \
            --branch=main \
            --path=clusters/iac

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Sealed Secrets key
        run: |
          kubectl create namespace security --dry-run=client -o yaml | kubectl apply -f -
          echo "${{ secrets.SEALED_SECRETS_KEY }}" > prv.key
          
          kubectl delete secret sealed-secrets-key -n security --ignore-not-found
          kubectl create secret tls sealed-secrets-key -n security --cert=./certs/sealed-secrets/secret.crt --key=./prv.key
          
          rm prv.key
          
          kubectl -n security label secret sealed-secrets-key sealedsecrets.bitnami.com/sealed-secrets-key=active

