name: IAC app changes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/iac-apps.yml"
      - "kubernetes/namespaces/**"

jobs:
  deploy-apps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set kubeconfig from Secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_SECRET }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Verify Cluster Connection
        run: |
          kubectl cluster-info
          echo "Connection to the cluster was successful."

      - name: Deploy namespaces
        run: |
          for manifest in kubernetes/namespaces/*.yaml; do
            if [ -f "$manifest" ]; then
              echo "Creating namespace: $manifest"
              kubectl apply -f "$manifest"
            fi
          done