name: IAC cluster changes

on:
  workflow_dispatch:
  push:
    paths:
      - "kubernetes/cluster/**"
      - ".github/workflows/iac-cluster.yml"

jobs:
  deploy-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key Files
        run: |
          mkdir -p ~/.ssh
          
          echo "${{ secrets.SSH_PRV_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_ed25519.pub
          chmod 600 ~/.ssh/id_ed25519.pub

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup helm
        uses: azure/setup-helm@v4.3.0

      - name: Setup hetzner-kubernetes
        run: |
          wget https://github.com/vitobotta/hetzner-k3s/releases/download/v2.3.9/hetzner-k3s-linux-amd64
          chmod +x hetzner-k3s-linux-amd64
          sudo mv hetzner-k3s-linux-amd64 /usr/local/bin/hetzner-k3s

      - name: Create or update cluster
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_KEY }}
        run: |
          hetzner-k3s create --config kubernetes/cluster/config.yml

      - name: Store kubeconfig as GitHub Secret
        run: |
          echo "${{ secrets.PA_SECRET_TOKEN }}" | gh auth login --with-token

          gh secret set KUBECONFIG_SECRET --body "$(cat kubeconfig)"

      - name: Setup Flux CLI
        uses: fluxcd/flux2/action@main

      - name: Bootstrap Flux CD
        run: |
          flux bootstrap github \
            --owner=${{ github.repository_owner }} \
            --repository=${{ github.event.repository.name }} \
            --branch=flux-cd \
            --path=clusters/iac-cluster \
            --token=${{ secrets.FLUX_CD_ADMIN_TOKEN }}

